-- AUTO GENERATED SYNC SCRIPT

-- Matrix Sablon
TRUNCATE TABLE sablon_matrix;
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('BOTOL', 0, 0, 1200, 850, 500, 500, 500, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('BOX DUS', 0, 0, 1500, 300, 200, 200, 200, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('CUP INJECT', 0, 0, 0, 400, 250, 220, 200, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('CUP PET', 0, 0, 0, 400, 250, 220, 200, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('CUP PP', 0, 0, 0, 260, 200, 170, 150, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('CUP GOCUP', 0, 0, 0, 260, 200, 170, 150, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('INJECT+TUTUP', 0, 0, 0, 400, 250, 220, 200, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('PAPERBOWL', 0, 0, 0, 400, 250, 220, 200, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('PAPERCUP', 0, 0, 0, 260, 200, 170, 150, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('PLASTIK', 0, 0, 0, 350, 250, 250, 250, 'AKTIF');
INSERT INTO sablon_matrix (category, min_1, min_10, min_100, min_500, min_1000, min_5000, min_10000, status) VALUES ('SEALER', 90000, 75000, 60000, 0, 0, 0, 0, 'AKTIF');

-- Addons
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-001', 'Jasa sablon a4+', 'ADDON', 'GLOBAL', 0, 700, 700, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-002', 'Sablon 2 warna', 'ADDON', 'GLOBAL', 0, 220, 220, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-003', 'Fast Track 1-3 hari', 'ADDON', 'GLOBAL', 0, 100000, 100000, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-004', 'Jasa Sablon a4', 'ADDON', 'GLOBAL', 0, 350, 350, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-005', 'SEDOTAN Steril (Kertas)', 'ADDON', 'GLOBAL', 0, 25500, 25500, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-006', 'SEDOTAN Papercup', 'ADDON', 'GLOBAL', 0, 15500, 15500, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-007', 'SEDOTAN Runcing (Bening / clear)', 'ADDON', 'GLOBAL', 0, 13750, 13750, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-008', 'SEDOTAN Runcing (Boba)', 'ADDON', 'GLOBAL', 0, 14000, 14000, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-009', 'SEDOTAN Runcing (Hitam)', 'ADDON', 'GLOBAL', 0, 8500, 8500, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-010', 'TUTUP CUP INJECT FLIP INJECT', 'ADDON', 'GLOBAL', 0, 560, 560, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-011', 'TUTUP CUP INJECT SAMBUNG HITAM', 'ADDON', 'GLOBAL', 0, 400, 400, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-012', 'TUTUP CUP INJECT SAMBUNG BENING GLOSSY', 'ADDON', 'GLOBAL', 0, 360, 360, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-013', 'TUTUP CUP INJECT SAMBUNG BENING FROST', 'ADDON', 'GLOBAL', 0, 280, 280, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-014', 'TUTUP CUP PET Strawless PET PLP', 'ADDON', 'GLOBAL', 0, 280, 280, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-015', 'TUTUP CUP PET Cembung PET Starindo', 'ADDON', 'GLOBAL', 0, 220, 220, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-016', 'TUTUP CUP PET Datar PET Starindo', 'ADDON', 'GLOBAL', 0, 220, 220, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-017', 'TUTUP CUP PET Strawless PET STARINDO', 'ADDON', 'GLOBAL', 0, 200, 200, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-018', 'TUTUP CUP PP Strawless pp besar', 'ADDON', 'GLOBAL', 0, 200, 200, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-019', 'TUTUP CUP PP Cembung Besar Starindo', 'ADDON', 'GLOBAL', 0, 160, 160, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-020', 'TUTUP CUP PP Datar Besar Starindo', 'ADDON', 'GLOBAL', 0, 140, 140, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-021', 'TUTUP CUP PP Datar Kecil Starindo', 'ADDON', 'GLOBAL', 0, 140, 140, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-022', 'TUTUP CUP PP Cembung Kecil Starindo', 'ADDON', 'GLOBAL', 0, 140, 140, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-023', 'TUTUP GOCUP STRAWLESS GOCUP', 'ADDON', 'GLOBAL', 0, 240, 240, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-024', 'TUTUP PAPERCUP Paper Cup DW 8 oz (Putih)', 'ADDON', 'GLOBAL', 0, 580, 580, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-025', 'TUTUP PAPERCUP Paper Cup DW 8 oz (Hitam)', 'ADDON', 'GLOBAL', 0, 580, 580, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-026', 'TUTUP PAPERCUP Papercup 9 OZ', 'ADDON', 'GLOBAL', 0, 260, 260, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;
INSERT INTO products (product_code, name, category, workshop_code, hpp_murni, base_price, price_polos, unit) VALUES ('ADD-027', 'TUTUP PAPERCUP Papercup 8 OZ', 'ADDON', 'GLOBAL', 0, 220, 220, 'PCS') ON CONFLICT (product_code) DO UPDATE SET name = EXCLUDED.name, base_price = EXCLUDED.base_price, price_polos = EXCLUDED.price_polos;

-- Products Update
UPDATE products SET category = 'BOTOL', workshop_code = 'GLOBAL', hpp_murni = 3400, base_price = 3740, price_polos = 4301 WHERE product_code = 'STG025';
UPDATE products SET category = 'BOTOL', workshop_code = 'GLOBAL', hpp_murni = 2300, base_price = 2530, price_polos = 2910 WHERE product_code = 'STG024';
UPDATE products SET category = 'BOTOL', workshop_code = 'GLOBAL', hpp_murni = 1800, base_price = 1980, price_polos = 2277 WHERE product_code = 'STG023';
UPDATE products SET category = 'BOTOL', workshop_code = 'GLOBAL', hpp_murni = 1080, base_price = 1188, price_polos = 1366 WHERE product_code = 'STG105';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 1350, base_price = 1485, price_polos = 1708 WHERE product_code = 'STG061';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 1250, base_price = 1375, price_polos = 1581 WHERE product_code = 'STG060';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 1200, base_price = 1320, price_polos = 1518 WHERE product_code = 'STG067';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 1100, base_price = 1210, price_polos = 1392 WHERE product_code = 'STG066';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 1050, base_price = 1155, price_polos = 1328 WHERE product_code = 'STG059';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 1000, base_price = 1100, price_polos = 1265 WHERE product_code = 'STG133';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 700, base_price = 770, price_polos = 885 WHERE product_code = 'STG046';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 616.6, base_price = 678, price_polos = 780 WHERE product_code = 'STG045';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 600, base_price = 660, price_polos = 759 WHERE product_code = 'STG137';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 530, base_price = 583, price_polos = 670 WHERE product_code = 'STG136';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 500, base_price = 550, price_polos = 633 WHERE product_code = 'STG044';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 490, base_price = 539, price_polos = 620 WHERE product_code = 'STG135';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 290, base_price = 319, price_polos = 367 WHERE product_code = 'STG126';
UPDATE products SET category = 'BOX DUS', workshop_code = 'GLOBAL', hpp_murni = 270, base_price = 297, price_polos = 342 WHERE product_code = 'STG127';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 710, base_price = 746, price_polos = 858 WHERE product_code = 'STG190';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 810, base_price = 851, price_polos = 979 WHERE product_code = 'STG175';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 655, base_price = 688, price_polos = 791 WHERE product_code = 'STG192';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 710, base_price = 746, price_polos = 858 WHERE product_code = 'STG206';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 810, base_price = 851, price_polos = 979 WHERE product_code = 'STG195';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 890, base_price = 935, price_polos = 1075 WHERE product_code = 'STG184';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 840.4, base_price = 882, price_polos = 1014 WHERE product_code = 'STG196';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 955, base_price = 1003, price_polos = 1153 WHERE product_code = 'STG179';
UPDATE products SET category = 'CUP PET', workshop_code = 'GUDANG', hpp_murni = 468, base_price = 491, price_polos = 565 WHERE product_code = 'STG100';
UPDATE products SET category = 'CUP PET', workshop_code = 'GUDANG', hpp_murni = 425, base_price = 446, price_polos = 513 WHERE product_code = 'STG005';
UPDATE products SET category = 'CUP PET', workshop_code = 'GUDANG', hpp_murni = 420, base_price = 441, price_polos = 507 WHERE product_code = 'STG129';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 492, base_price = 517, price_polos = 595 WHERE product_code = 'STG013';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 492, base_price = 517, price_polos = 595 WHERE product_code = 'STG014';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 436, base_price = 458, price_polos = 527 WHERE product_code = 'STG099';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 435, base_price = 457, price_polos = 526 WHERE product_code = 'STG003';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 426, base_price = 447, price_polos = 514 WHERE product_code = 'STG010';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 426, base_price = 447, price_polos = 514 WHERE product_code = 'STG012';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 415, base_price = 436, price_polos = 501 WHERE product_code = 'STG002';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 410, base_price = 431, price_polos = 496 WHERE product_code = 'STG183';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 395, base_price = 415, price_polos = 477 WHERE product_code = 'STG011';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 394, base_price = 414, price_polos = 476 WHERE product_code = 'STG007';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 394, base_price = 414, price_polos = 476 WHERE product_code = 'STG009';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 390, base_price = 410, price_polos = 471 WHERE product_code = 'STG004';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 244, base_price = 256, price_polos = 294 WHERE product_code = 'STG001';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 244, base_price = 256, price_polos = 294 WHERE product_code = 'STG006';
UPDATE products SET category = 'CUP PP', workshop_code = 'GUDANG', hpp_murni = 244, base_price = 256, price_polos = 294 WHERE product_code = 'STG008';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 460, base_price = 483, price_polos = 555 WHERE product_code = 'STG167';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 425.131, base_price = 446, price_polos = 513 WHERE product_code = 'STG173';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 423.713, base_price = 445, price_polos = 512 WHERE product_code = 'STG172';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 421.369, base_price = 442, price_polos = 508 WHERE product_code = 'STG166';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 400.837, base_price = 421, price_polos = 484 WHERE product_code = 'STG165';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 400, base_price = 420, price_polos = 483 WHERE product_code = 'STG168';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 397, base_price = 417, price_polos = 480 WHERE product_code = 'STG171';
UPDATE products SET category = 'CUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 372, base_price = 391, price_polos = 450 WHERE product_code = 'STG170';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 1065, base_price = 1118, price_polos = 1286 WHERE product_code = 'STG186';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 884, base_price = 928, price_polos = 1067 WHERE product_code = 'STG182';
UPDATE products SET category = 'CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 800, base_price = 840, price_polos = 966 WHERE product_code = 'STG194';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 900, base_price = 945, price_polos = 1087 WHERE product_code = 'STG180';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 1100, base_price = 1155, price_polos = 1328 WHERE product_code = 'STG189';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 648, base_price = 680, price_polos = 782 WHERE product_code = 'STG191';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 1078, base_price = 1132, price_polos = 1302 WHERE product_code = 'STG181';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 1080, base_price = 1134, price_polos = 1304 WHERE product_code = 'STG176';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 1050, base_price = 1103, price_polos = 1268 WHERE product_code = 'STG193';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 1150, base_price = 1208, price_polos = 1389 WHERE product_code = 'STG177';
UPDATE products SET category = 'INJECT+TUTUP', workshop_code = 'GUDANG', hpp_murni = 774, base_price = 813, price_polos = 935 WHERE product_code = 'STG178';
UPDATE products SET category = 'Jasa Layanan', workshop_code = 'KING', hpp_murni = 0, base_price = 0, price_polos = 0 WHERE product_code = 'PRD-29491';
UPDATE products SET category = 'Jasa Layanan', workshop_code = 'KING', hpp_murni = 0, base_price = 0, price_polos = 0 WHERE product_code = 'PRD-32989';
UPDATE products SET category = 'Jasa Layanan', workshop_code = 'KING', hpp_murni = 0, base_price = 0, price_polos = 0 WHERE product_code = 'PRD-33307';
UPDATE products SET category = 'Jasa Layanan', workshop_code = 'KING', hpp_murni = 0, base_price = 0, price_polos = 0 WHERE product_code = 'PRD-34260';
UPDATE products SET category = 'PAPERBOWL', workshop_code = 'GUDANG', hpp_murni = 1076, base_price = 1130, price_polos = 1300 WHERE product_code = 'STG022';
UPDATE products SET category = 'PAPERBOWL', workshop_code = 'GUDANG', hpp_murni = 1048, base_price = 1100, price_polos = 1265 WHERE product_code = 'STG021';
UPDATE products SET category = 'PAPERBOWL', workshop_code = 'GUDANG', hpp_murni = 909, base_price = 954, price_polos = 1097 WHERE product_code = 'STG020';
UPDATE products SET category = 'PAPERBOWL', workshop_code = 'GUDANG', hpp_murni = 884, base_price = 928, price_polos = 1067 WHERE product_code = 'STG019';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 744, base_price = 781, price_polos = 898 WHERE product_code = 'STG148';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 644, base_price = 676, price_polos = 777 WHERE product_code = 'STG142';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 635, base_price = 667, price_polos = 767 WHERE product_code = 'STG143';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 383, base_price = 402, price_polos = 462 WHERE product_code = 'STG018';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 285, base_price = 299, price_polos = 344 WHERE product_code = 'STG017';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 262, base_price = 275, price_polos = 316 WHERE product_code = 'STG187';
UPDATE products SET category = 'PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 260, base_price = 273, price_polos = 314 WHERE product_code = 'STG015';
UPDATE products SET category = 'SEALER', workshop_code = 'GLOBAL', hpp_murni = 47000, base_price = 51700, price_polos = 59455 WHERE product_code = 'STG132';
UPDATE products SET category = 'SEALER', workshop_code = 'GLOBAL', hpp_murni = 45000, base_price = 49500, price_polos = 56925 WHERE product_code = 'STG130';
UPDATE products SET category = 'SEALER', workshop_code = 'GLOBAL', hpp_murni = 42000, base_price = 46200, price_polos = 53130 WHERE product_code = 'STG131';
UPDATE products SET category = 'SEALER', workshop_code = 'GLOBAL', hpp_murni = 31250, base_price = 34375, price_polos = 39531 WHERE product_code = 'STG079';
UPDATE products SET category = 'SEALER', workshop_code = 'GLOBAL', hpp_murni = 26000, base_price = 28600, price_polos = 32890 WHERE product_code = 'STG162';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 16000, base_price = 17600, price_polos = 20240 WHERE product_code = 'STG039';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 16000, base_price = 17600, price_polos = 20240 WHERE product_code = 'STG040';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 1045.454545, base_price = 1150, price_polos = 1323 WHERE product_code = 'STG164';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 657.1428571, base_price = 723, price_polos = 831 WHERE product_code = 'STG113';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 633.3333333, base_price = 697, price_polos = 802 WHERE product_code = 'STG114';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 600, base_price = 660, price_polos = 759 WHERE product_code = 'STG151';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 575, base_price = 633, price_polos = 728 WHERE product_code = 'STG112';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 563.6363636, base_price = 620, price_polos = 713 WHERE product_code = 'STG174';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 533.3333333, base_price = 587, price_polos = 675 WHERE product_code = 'STG043';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 500, base_price = 550, price_polos = 633 WHERE product_code = 'STG042';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 475, base_price = 523, price_polos = 601 WHERE product_code = 'STG033';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 417.5, base_price = 459, price_polos = 528 WHERE product_code = 'STG110';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 400, base_price = 440, price_polos = 506 WHERE product_code = 'STG041';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 330, base_price = 363, price_polos = 417 WHERE product_code = 'STG032';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 293.75, base_price = 323, price_polos = 371 WHERE product_code = 'STG188';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 287.5, base_price = 316, price_polos = 363 WHERE product_code = 'STG111';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 220, base_price = 242, price_polos = 278 WHERE product_code = 'STG121';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 185, base_price = 204, price_polos = 235 WHERE product_code = 'STG030';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 142.8571429, base_price = 157, price_polos = 181 WHERE product_code = 'STG120';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 75, base_price = 83, price_polos = 95 WHERE product_code = 'STG029';
UPDATE products SET category = 'PLASTIK', workshop_code = 'GLOBAL', hpp_murni = 40, base_price = 44, price_polos = 51 WHERE product_code = 'STG031';
UPDATE products SET category = 'SEDOTAN', workshop_code = 'GLOBAL', hpp_murni = 20500, base_price = 22550, price_polos = 25932 WHERE product_code = 'STG086';
UPDATE products SET category = 'SEDOTAN', workshop_code = 'GLOBAL', hpp_murni = 12500, base_price = 13750, price_polos = 15812 WHERE product_code = 'STG119';
UPDATE products SET category = 'SEDOTAN', workshop_code = 'GLOBAL', hpp_murni = 12250, base_price = 13475, price_polos = 15496 WHERE product_code = 'STG138';
UPDATE products SET category = 'SEDOTAN', workshop_code = 'GLOBAL', hpp_murni = 11000, base_price = 12100, price_polos = 13915 WHERE product_code = 'STG088';
UPDATE products SET category = 'SEDOTAN', workshop_code = 'GLOBAL', hpp_murni = 7000, base_price = 7700, price_polos = 8855 WHERE product_code = 'STG087';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 134000, base_price = 147400, price_polos = 169510 WHERE product_code = 'DS-024';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 105296.0714, base_price = 115826, price_polos = 133200 WHERE product_code = 'DS-014';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 105261.25, base_price = 115787, price_polos = 133155 WHERE product_code = 'DS-030';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 102296.0714, base_price = 112526, price_polos = 129405 WHERE product_code = 'DS-018';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 100000, base_price = 110000, price_polos = 126500 WHERE product_code = 'DS-025';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 99000, base_price = 108900, price_polos = 125235 WHERE product_code = 'DS-021';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 98000, base_price = 107800, price_polos = 123970 WHERE product_code = 'DS-013';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 97000, base_price = 106700, price_polos = 122705 WHERE product_code = 'DS-028';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 94000, base_price = 103400, price_polos = 118910 WHERE product_code = 'DS-023';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 92000, base_price = 101200, price_polos = 116380 WHERE product_code = 'DS-011';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 91296.07143, base_price = 100426, price_polos = 115490 WHERE product_code = 'DS-032';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 90261.25, base_price = 99287, price_polos = 114180 WHERE product_code = 'DS-020';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 90000, base_price = 99000, price_polos = 113850 WHERE product_code = 'DS-001';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 90000, base_price = 99000, price_polos = 113850 WHERE product_code = 'DS-016';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 90000, base_price = 99000, price_polos = 113850 WHERE product_code = 'DS-017';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 90000, base_price = 99000, price_polos = 113850 WHERE product_code = 'DS-031';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 90000, base_price = 99000, price_polos = 113850 WHERE product_code = 'DS-033';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 89000, base_price = 97900, price_polos = 112585 WHERE product_code = 'DS-015';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 88000, base_price = 96800, price_polos = 111320 WHERE product_code = 'DS-010';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 87000, base_price = 95700, price_polos = 110055 WHERE product_code = 'DS-004';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 87000, base_price = 95700, price_polos = 110055 WHERE product_code = 'DS-005';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 86058.49057, base_price = 94664, price_polos = 108864 WHERE product_code = 'DS-003';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 86000, base_price = 94600, price_polos = 108790 WHERE product_code = 'DS-027';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 85000, base_price = 93500, price_polos = 107525 WHERE product_code = 'DS-006';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 85000, base_price = 93500, price_polos = 107525 WHERE product_code = 'DS-012';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 85000, base_price = 93500, price_polos = 107525 WHERE product_code = 'DS-026';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 84261.25, base_price = 92687, price_polos = 106590 WHERE product_code = 'DS-007';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 84261.25, base_price = 92687, price_polos = 106590 WHERE product_code = 'DS-008';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 84000, base_price = 92400, price_polos = 106260 WHERE product_code = 'DS-009';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 83500, base_price = 91850, price_polos = 105627 WHERE product_code = 'DS-002';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 79000, base_price = 86900, price_polos = 99935 WHERE product_code = 'DS-019';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 70000, base_price = 77000, price_polos = 88550 WHERE product_code = 'DS-029';
UPDATE products SET category = 'TINTA', workshop_code = 'GLOBAL', hpp_murni = 39083.33333, base_price = 42992, price_polos = 49441 WHERE product_code = 'DS-022';
UPDATE products SET category = 'TUTUP CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 550, base_price = 578, price_polos = 665 WHERE product_code = 'STG185';
UPDATE products SET category = 'TUTUP CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 385, base_price = 404, price_polos = 465 WHERE product_code = 'STG203';
UPDATE products SET category = 'TUTUP CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 350, base_price = 368, price_polos = 423 WHERE product_code = 'STG201';
UPDATE products SET category = 'TUTUP CUP INJECT', workshop_code = 'GUDANG', hpp_murni = 260, base_price = 273, price_polos = 314 WHERE product_code = 'STG202';
UPDATE products SET category = 'TUTUP CUP PET', workshop_code = 'GUDANG', hpp_murni = 210, base_price = 221, price_polos = 254 WHERE product_code = 'STG106';
UPDATE products SET category = 'TUTUP CUP PET', workshop_code = 'GUDANG', hpp_murni = 180, base_price = 189, price_polos = 217 WHERE product_code = 'STG082';
UPDATE products SET category = 'TUTUP CUP PET', workshop_code = 'GUDANG', hpp_murni = 180, base_price = 189, price_polos = 217 WHERE product_code = 'STG083';
UPDATE products SET category = 'TUTUP CUP PET', workshop_code = 'GUDANG', hpp_murni = 175, base_price = 184, price_polos = 212 WHERE product_code = 'STG163';
UPDATE products SET category = 'TUTUP CUP PP', workshop_code = 'GUDANG', hpp_murni = 175, base_price = 184, price_polos = 212 WHERE product_code = 'STG149';
UPDATE products SET category = 'TUTUP CUP PP', workshop_code = 'GUDANG', hpp_murni = 135, base_price = 142, price_polos = 163 WHERE product_code = 'STG081';
UPDATE products SET category = 'TUTUP CUP PP', workshop_code = 'GUDANG', hpp_murni = 113, base_price = 119, price_polos = 137 WHERE product_code = 'STG134';
UPDATE products SET category = 'TUTUP CUP PP', workshop_code = 'GUDANG', hpp_murni = 113, base_price = 119, price_polos = 137 WHERE product_code = 'STG146';
UPDATE products SET category = 'TUTUP CUP PP', workshop_code = 'GUDANG', hpp_murni = 103, base_price = 108, price_polos = 124 WHERE product_code = 'STG080';
UPDATE products SET category = 'TUTUP GOCUP', workshop_code = 'GUDANG', hpp_murni = 172, base_price = 181, price_polos = 208 WHERE product_code = 'STG205';
UPDATE products SET category = 'TUTUP PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 520, base_price = 546, price_polos = 628 WHERE product_code = 'STG144';
UPDATE products SET category = 'TUTUP PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 520, base_price = 546, price_polos = 628 WHERE product_code = 'STG145';
UPDATE products SET category = 'TUTUP PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 225, base_price = 236, price_polos = 271 WHERE product_code = 'STG085';
UPDATE products SET category = 'TUTUP PAPERCUP', workshop_code = 'GUDANG', hpp_murni = 185, base_price = 194, price_polos = 223 WHERE product_code = 'STG084';

-- Satuan Produk
DELETE FROM product_units WHERE product_code IN ('STG025','STG024','STG023','STG105','STG061','STG060','STG067','STG066','STG059','STG133','STG046','STG045','STG137','STG136','STG044','STG135','STG126','STG127','STG190','STG175','STG192','STG206','STG195','STG184','STG196','STG179','STG100','STG005','STG129','STG013','STG014','STG099','STG003','STG010','STG012','STG002','STG183','STG011','STG007','STG009','STG004','STG001','STG006','STG008','STG167','STG173','STG172','STG166','STG165','STG168','STG171','STG170','STG186','STG182','STG194','STG180','STG189','STG191','STG181','STG176','STG193','STG177','STG178','PRD-29491','PRD-32989','PRD-33307','PRD-34260','STG022','STG021','STG020','STG019','STG148','STG142','STG143','STG018','STG017','STG187','STG015','STG132','STG130','STG131','STG079','STG162','STG039','STG040','STG164','STG113','STG114','STG151','STG112','STG174','STG043','STG042','STG033','STG110','STG041','STG032','STG188','STG111','STG121','STG030','STG120','STG029','STG031','STG086','STG119','STG138','STG088','STG087','DS-024','DS-014','DS-030','DS-018','DS-025','DS-021','DS-013','DS-028','DS-023','DS-011','DS-032','DS-020','DS-001','DS-016','DS-017','DS-031','DS-033','DS-015','DS-010','DS-004','DS-005','DS-003','DS-027','DS-006','DS-012','DS-026','DS-007','DS-008','DS-009','DS-002','DS-019','DS-029','DS-022','STG185','STG203','STG201','STG202','STG106','STG082','STG083','STG163','STG149','STG081','STG134','STG146','STG080','STG205','STG144','STG145','STG085','STG084');
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG025', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG024', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG023', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG105', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG061', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG060', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG067', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG066', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG059', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG133', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG046', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG045', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG137', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG136', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG044', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG135', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG126', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG127', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG190', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG175', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG192', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG206', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG195', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG184', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG196', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG179', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG100', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG005', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG129', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG013', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG014', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG099', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG003', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG010', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG012', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG002', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG183', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG011', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG007', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG009', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG004', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG001', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG006', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG008', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG167', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG173', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG172', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG166', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG165', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG168', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG171', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG170', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG186', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG182', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG194', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG180', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG189', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG191', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG181', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG176', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG193', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG177', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG178', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('PRD-29491', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('PRD-32989', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('PRD-33307', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('PRD-34260', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG022', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG021', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG020', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG019', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG148', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG142', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG143', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG018', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG017', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG187', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG015', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG132', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG130', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG131', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG079', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG162', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG039', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG040', 'PACK', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG164', 'PACK', 22);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG113', 'PACK', 35);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG114', 'PACK', 30);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG151', 'PACK', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG112', 'PACK', 20);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG174', 'PACK', 55);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG043', 'PACK', 30);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG042', 'PACK', 30);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG033', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG110', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG041', 'PACK', 35);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG032', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG188', 'PACK', 80);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG111', 'PACK', 40);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG121', 'PACK', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG030', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG120', 'PACK', 35);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG029', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG031', 'PACK', 100);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG086', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG119', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG138', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG088', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG087', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-024', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-014', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-030', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-018', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-025', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-021', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-013', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-028', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-023', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-011', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-032', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-020', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-001', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-016', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-017', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-031', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-033', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-015', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-010', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-004', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-005', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-003', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-027', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-006', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-012', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-026', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-007', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-008', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-009', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-002', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-019', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-029', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('DS-022', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG185', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG203', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG201', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG202', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG106', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG082', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG083', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG163', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG149', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG081', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG134', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG146', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG080', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG205', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG144', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG145', 'DUS', 500);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG085', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG084', 'DUS', 1000);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG025', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG024', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG023', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG105', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG061', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG060', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG067', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG066', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG059', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG133', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG046', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG045', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG137', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG136', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG044', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG135', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG126', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG127', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG190', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG175', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG192', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG206', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG195', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG184', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG196', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG179', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG100', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG005', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG129', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG013', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG014', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG099', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG003', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG010', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG012', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG002', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG183', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG011', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG007', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG009', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG004', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG001', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG006', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG008', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG167', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG173', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG172', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG166', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG165', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG168', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG171', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG170', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG186', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG182', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG194', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG180', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG189', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG191', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG181', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG176', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG193', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG177', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG178', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG022', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG021', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG020', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG019', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG148', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG142', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG143', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG018', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG017', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG187', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG015', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG132', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG130', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG131', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG079', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG162', 'PACK', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG039', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG040', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG164', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG113', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG114', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG151', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG112', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG174', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG043', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG042', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG033', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG110', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG041', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG032', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG188', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG111', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG121', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG030', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG120', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG029', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG031', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG185', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG203', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG201', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG202', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG106', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG082', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG083', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG163', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG149', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG081', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG134', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG146', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG080', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG205', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG144', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG145', 'ROLL', 25);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG085', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG084', 'ROLL', 50);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG190', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG175', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG192', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG206', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG195', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG184', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG196', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG179', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG100', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG005', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG129', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG013', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG014', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG099', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG003', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG010', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG012', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG002', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG183', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG011', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG007', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG009', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG004', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG001', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG006', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG008', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG167', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG173', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG172', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG166', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG165', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG168', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG171', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG170', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG186', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG182', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG194', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG180', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG189', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG191', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG181', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG176', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG193', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG177', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG178', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG022', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG021', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG020', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG019', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG148', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG142', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG143', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG018', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG017', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG187', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG015', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG185', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG203', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG201', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG202', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG106', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG082', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG083', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG163', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG149', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG081', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG134', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG146', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG080', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG205', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG144', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG145', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG085', 'PCS', 1);
INSERT INTO product_units (product_code, unit_name, multiplier) VALUES ('STG084', 'PCS', 1);
